"""
train_isolation_forest.py
--------------------------
Trains an Isolation Forest on daily behavioral features and exports it as
a plain C header (arrays + comparisons, no ML runtime library) for the
ESP32-S3 to run on-device.

Implements the ORIGINAL Isolation Forest scoring formula (Liu, Ting & Zhou,
2008) directly, rather than relying on sklearn's score_samples() sign
convention -- this guarantees the threshold picked here means exactly the
same thing as the score the C runtime computes, since both use identical
math.

Features are intentionally NOT standardized/normalized: the ESP32-S3 feeds
RAW values (counts, seconds) into the scorer, so the exported split
thresholds must live in raw-value space too. ExtraTree split selection is
scale-invariant, so skipping scaling costs nothing.

After exporting, the script re-parses the generated header and re-implements
the C scoring algorithm over it (the same integer/float arrays the firmware
will run), verifying bit-for-bit agreement with the Python scorer.

Usage:
    pip install pandas numpy scikit-learn
    python train_isolation_forest.py --features features.csv --out isolation_forest_model.h
"""

import argparse
import math
import numpy as np
import pandas as pd
from sklearn.ensemble import IsolationForest

FEATURE_NAMES = [
    "bathroom_visit_count",
    "bathroom_total_duration_sec",
    "bathroom_max_duration_sec",
    "wake_time_sec_of_day",
]


def c_factor(n: float) -> float:
    """Average path length of an unsuccessful BST search over n points."""
    if n <= 1:
        return 0.0
    if n == 2:
        return 1.0
    euler_mascheroni = 0.5772156649
    return 2.0 * (math.log(n - 1) + euler_mascheroni) - (2.0 * (n - 1) / n)


def path_length(tree, x, node=0, depth=0):
    """Walk a single fitted tree (sklearn's underlying ExtraTree) for one
    sample, returning depth-reached + c(leaf sample count)."""
    left = tree.children_left[node]
    right = tree.children_right[node]
    if left == -1 and right == -1:  # leaf
        return depth + c_factor(tree.n_node_samples[node])
    feat = tree.feature[node]
    thresh = tree.threshold[node]
    if x[feat] <= thresh:
        return path_length(tree, x, left, depth + 1)
    else:
        return path_length(tree, x, right, depth + 1)


def anomaly_score(model: IsolationForest, X: np.ndarray, max_samples: int) -> np.ndarray:
    """Own implementation of the IF anomaly score, matching the C runtime
    exactly: s(x) close to 1 -> anomalous, close to 0.5 or below -> normal."""
    scores = np.zeros(len(X))
    for est in model.estimators_:
        tree = est.tree_
        for i, x in enumerate(X):
            scores[i] += path_length(tree, x)
    avg_h = scores / len(model.estimators_)
    cn = c_factor(max_samples)
    return np.power(2.0, -avg_h / cn)


def export_to_c_header(model: IsolationForest, max_samples: int, threshold: float,
                        feature_names, out_path: str):
    node_feature, node_threshold, node_left, node_right, node_samples = [], [], [], [], []
    tree_offsets = [0]

    for est in model.estimators_:
        tree = est.tree_
        base = tree_offsets[-1]  # absolute index of THIS tree's root in the flattened arrays
        for i in range(tree.node_count):
            node_feature.append(int(tree.feature[i]))
            node_threshold.append(float(tree.threshold[i]))
            # CRITICAL: sklearn stores children as TREE-LOCAL preorder indices
            # (root = 0, leaves = -1). The C runtime indexes the FLATTENED
            # absolute arrays, so child indices must be rebased by this
            # tree's starting offset. Without this, tree 1..N walk into
            # tree 0's nodes and the on-device scores are wrong (this was a
            # silent score-parity bug; the self-check now catches it).
            node_left.append(base + int(tree.children_left[i]) if int(tree.children_left[i]) >= 0 else -1)
            node_right.append(base + int(tree.children_right[i]) if int(tree.children_right[i]) >= 0 else -1)
            node_samples.append(int(tree.n_node_samples[i]))
        tree_offsets.append(tree_offsets[-1] + tree.node_count)

    num_trees = len(model.estimators_)
    total_nodes = len(node_feature)

    def c_array(name, values, ctype="int"):
        vals = ", ".join(
            f"{v:.6f}f" if ctype == "float" else str(v) for v in values
        )
        return f"static const {ctype} {name}[{len(values)}] = {{ {vals} }};\n"

    with open(out_path, "w") as f:
        f.write("// Auto-generated by train_isolation_forest.py -- do not hand-edit.\n")
        f.write("#pragma once\n\n")
        f.write(f"#define IF_NUM_TREES {num_trees}\n")
        f.write(f"#define IF_NUM_FEATURES {len(feature_names)}\n")
        f.write(f"#define IF_MAX_SAMPLES {max_samples}\n")
        f.write(f"#define IF_ANOMALY_THRESHOLD {threshold:.6f}f\n\n")

        f.write("// Feature order -- the caller's float[] MUST follow this exact order:\n")
        for i, name in enumerate(feature_names):
            f.write(f"// [{i}] {name}\n")
        f.write("\n")

        f.write(c_array("if_tree_offsets", tree_offsets, "int"))
        f.write(c_array("if_node_feature", node_feature, "int"))
        f.write(c_array("if_node_threshold", node_threshold, "float"))
        f.write(c_array("if_node_left", node_left, "int"))
        f.write(c_array("if_node_right", node_right, "int"))
        f.write(c_array("if_node_samples", node_samples, "int"))

    print(f"Exported {num_trees} trees, {total_nodes} total nodes -> {out_path}")


def verify_exported_header(header_path: str, model: IsolationForest,
                           X: np.ndarray, max_samples: int, py_scores: np.ndarray) -> bool:
    """
    Re-implements the C scoring algorithm from isolation_forest_runtime.h
    directly over the arrays written into the exported header, then compares
    each training sample's score against anomaly_score(). This proves the
    header the device will be flashed with scores identically to the model
    that was trained here. Returns True on agreement (max abs diff < 1e-4).
    """
    import re

    txt = open(header_path, "r").read()

    def int_array(name: str):
        m = re.search(rf"{name}\[\d+\]\s*=\s*\{{([^}}]*)\}}", txt, re.S)
        return [int(x) for x in m.group(1).split(",")]

    def float_array(name: str):
        m = re.search(rf"{name}\[\d+\]\s*=\s*\{{([^}}]*)\}}", txt, re.S)
        # entries look like " -2.000000f " -- strip whitespace and the 'f' suffix
        return [float(x.strip().rstrip("f")) for x in m.group(1).split(",")]

    offsets = int_array("if_tree_offsets")
    feat = int_array("if_node_feature")
    thresh = float_array("if_node_threshold")
    left = int_array("if_node_left")
    right = int_array("if_node_right")
    samples = int_array("if_node_samples")

    def c_factor(n):
        if n <= 1:
            return 0.0
        if n == 2:
            return 1.0
        return 2.0 * (math.log(n - 1) + 0.5772156649) - 2.0 * (n - 1) / n

    def c_path_length(tree_idx, x):
        # Mirror of ifPathLength() in isolation_forest_runtime.h.
        node = offsets[tree_idx]
        depth = 0
        while True:
            l, r = left[node], right[node]
            if l == -1 and r == -1:
                return depth + c_factor(samples[node])
            node = left[node] if x[feat[node]] <= thresh[node] else right[node]
            depth += 1

    reimplemented = []
    for x in X:
        total_h = sum(c_path_length(t, x) for t in range(len(model.estimators_)))
        avg_h = total_h / len(model.estimators_)
        cn = c_factor(max_samples)
        reimplemented.append(2.0 ** (-avg_h / cn))

    diff = np.abs(np.asarray(reimplemented) - py_scores).max()
    print(f"Header-vs-Python score parity: max abs diff = {diff:.3e} "
          f"(threshold for pass: 1e-4)")
    return diff < 1e-4


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--features", required=True, help="CSV produced by extract_features.py")
    ap.add_argument("--out", default="isolation_forest_model.h")
    ap.add_argument("--n-estimators", type=int, default=30, help="Keep modest -- each tree adds flash usage")
    ap.add_argument("--max-samples", type=int, default=64)
    ap.add_argument("--threshold-percentile", type=float, default=95,
                     help="Training-data percentile used as the anomaly cutoff")
    args = ap.parse_args()

    df = pd.read_csv(args.features)

    # --- Robust feature selection: never train on an all-NaN column. -------
    # Only a TRAILING subset may be dropped: the firmware feeds its feature
    # vector in FEATURE_NAMES order into the scorer, so dropping anything
    # other than a suffix would silently misalign every tree split.
    used_names = list(FEATURE_NAMES)
    for name in FEATURE_NAMES:
        if df[name].isna().all():
            print(f"WARNING: feature '{name}' is NaN for every row -- dropping it from the model.")
            used_names.remove(name)
    dropped_pos = [FEATURE_NAMES.index(n) for n in FEATURE_NAMES if n not in used_names]
    suffix_expected = list(range(len(FEATURE_NAMES) - len(used_names), len(FEATURE_NAMES)))
    if dropped_pos and dropped_pos != suffix_expected:
        raise SystemExit(
            f"FATAL: all-NaN features must form a trailing suffix of {FEATURE_NAMES} "
            f"so the on-device feature vector stays aligned. Got positions {dropped_pos}.")
    if not used_names:
        raise SystemExit("FATAL: every feature is all-NaN -- nothing to train on. "
                         "Fix extract_features.py first (see its diagnostics).")

    # Drop days that are missing any USED feature (e.g. a day with no
    # qualifying sleep episode and therefore no wake time).
    before = len(df)
    df = df.dropna(subset=used_names)
    if len(df) < before:
        print(f"Dropped {before - len(df)}/{before} days that had missing values "
              f"in {used_names}.")
    if len(df) < 14:
        print(f"WARNING: only {len(df)} complete days available -- "
              f"the model will be weak until you have several weeks of data. "
              f"Proceeding anyway.")
    if len(df) < 4 or len(used_names) < 2:
        raise SystemExit(f"FATAL: only {len(df)} days x {len(used_names)} features remain -- "
                         f"not enough to fit an Isolation Forest. Collect more data or fix "
                         f"feature extraction.")
    print(f"Training on {len(df)} days x {len(used_names)} features: {used_names}")
    print()

    X = df[used_names].to_numpy(dtype=float)
    max_samples = min(args.max_samples, len(X))

    model = IsolationForest(
        n_estimators=args.n_estimators,
        max_samples=max_samples,
        contamination="auto",
        random_state=42,
    )
    model.fit(X)

    scores = anomaly_score(model, X, max_samples)
    threshold = float(np.percentile(scores, args.threshold_percentile))

    print(f"Training anomaly score stats: min={scores.min():.3f} "
          f"mean={scores.mean():.3f} max={scores.max():.3f}")
    print(f"Chosen ANOMALY_THRESHOLD (p{args.threshold_percentile}) = {threshold:.3f}")
    flagged = df.loc[scores >= threshold, ["date"] + used_names]
    print(f"Rows flagged as anomalous AT the chosen threshold "
          f"({len(flagged)} day(s) -- sanity check, should be a small minority):")
    print(flagged.to_string(index=False))
    print()

    export_to_c_header(model, max_samples, threshold, used_names, args.out)

    # Optional self-check: re-implement the exported C scorer over the
    # generated arrays and confirm it matches the Python scorer closely.
    if verify_exported_header(args.out, model, X, max_samples, scores):
        print("Self-check OK: the exported header's C scoring algorithm reproduces "
              "the Python anomaly scores.")
    else:
        raise SystemExit("FATAL: exported header does not reproduce the training scores -- "
                         "do NOT flash this model to the device.")


if __name__ == "__main__":
    main()
